/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.gindix.interview;


import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;

class StrDecoderTest {

    void testCode(String inputString,String expectedOutput){
        StringBuilder output = new StringBuilder();

        StrDecoder decoder = new StrDecoder(inputString);
        while(decoder.hasNext()){
            output.append(decoder.next());
        }
        assertTrue(output.toString().equals(expectedOutput));
    }

    @Test void zeroLengthChars() {
       assertThrows(AssertionError.class, () -> {
            new StrDecoder("");
        });
    }

    @Test void nonNumericChars() {
       assertThrows(AssertionError.class, () -> {
            new StrDecoder("12a");
        });
    }

    @Test void testInput1(){
        testCode("1341", "31111");
    }

    @Test void testInput2(){
        testCode("482714", "8888774");
    }

    @Test void testInput3(){
        testCode("082714", "774");
    }

    @Test void testInput4(){
        testCode("080724", "44");
    }

    @Test void testInput5(){
        testCode("080704", "");
    }
    
}
